SELECT C.ID_CLIENTE, C.NOME, C.EMAIL,  F.ID_CPF, F.NASCIMENTO, S.DESCRICAO
FROM
CLIENTE C
JOIN
FISICA F
ON
C.ID_CLIENTE  = F.CLIENTE_ID_CLIENTE
JOIN
SEXO S
ON
S.ID_SEXO = F.SEXO_ID_SEXO;

SELECT C.ID_CLIENTE, C.NOME, C.EMAIL, J.ID_CNPJ, J.ABERTURA, J.INSCRICAO_ESTADUAL, J.RAZAO_SOCIAL
FROM
CLIENTE C
JOIN
JURIDICA J
ON
J.CLIENTE_ID_CLIENTE = C.ID_CLIENTE;

SELECT J.RAZAO_SOCIAL,  J.ID_CNPJ , J.INSCRICAO_ESTADUAL,T.DDD, T.CELULAR , E.TIPO_LOGRADOURO, E.NOME_LOGRADOURO, E.NUMERO, E.CEP, E.CIDADE, ES.SIGLA  
FROM
CLIENTE C
INNER JOIN
JURIDICA J  
ON
J.CLIENTE_ID_CLIENTE  = C.ID_CLIENTE
INNER JOIN
TELEFONE T
ON
T.CLIENTE_ID_CLIENTE = C.ID_CLIENTE 
INNER JOIN 
CLIENTE_ENDERECO CE
ON
CE.CLIENTE_ID_ENDERECO = C.ID_CLIENTE
INNER JOIN 
ENDERECO E
ON
CE.ENDERECO_ID_ENDERECO = E.ID_ENDERECO
INNER JOIN
ESTADO ES
ON
E.ESTADO_ID_ESTADO = ES.ID_ESTADO;