-- Query Detalhes pedido pessoa juridica
SELECT
P.ID_PEDIDO AS CODIGO,
DATE_FORMAT(P.DATA_PEDIDO, '%d-%m-%Y') AS 'DATA',
J.RAZAO_SOCIAL AS NOME,
CONCAT(SUBSTR(J.ID_CNPJ, 1,9),'/', SUBSTR(J.ID_CNPJ, 10,14))  AS 'CPF/CNPJ',
C.EMAIL AS EMAIL,
CONCAT(T.DDD, ' ', SUBSTR(T.FIXO, 1,4),'-', SUBSTR(T.FIXO, 5,8)) AS CONTATO,
PD.DESCRICAO AS PRODUTO,
PD.VOLUME AS VOLUME,
PD.PESO AS PESO,
PD.PRECO AS PRECO,
IP.QUANTIDADE AS QUANTIDADE , 
P.VALOR_TOTAL AS TOTAL,
E.APELIDO AS ENTREGA,
CONCAT(E.TIPO_LOGRADOURO,' ', E.NOME_LOGRADOURO, ' ','-', ' ', E.NUMERO) AS ENDERECO,
CONCAT(SUBSTR(E.CEP, 1,5), '-', SUBSTR(E.CEP, 6,9) ) AS CEP,
CONCAT(E.CIDADE,'-',ES.SIGLA) AS MUNICIPIO, 
SP.DESCRICAO AS STATUS_PEDIDO,
PG.STATUS_PAGAMENTO AS STATUS_PAGAMENTO,
FP.INSTITUICAO AS INSTITUICAO,
PG.VALOR_PAGAMENTO AS VALOR_PAGO,
DATE_FORMAT(PG.DATA_PAGAMENTO, '%d-%m-%Y') AS 'DATA',
FENT.EMPRESA AS ENTREGADOR,
ENT.PRAZO_ESTIMADO AS PRAZO_ENTREGA,
ENT.VALOR AS FRETE,
TSE.DESCRICAO AS STATUS_ENTREGA,
DATE_FORMAT(SE.DATA_ENTREGA, '%d-%m-%Y') AS 'DATA'    
FROM
PEDIDO P
INNER JOIN
ITEM_PEDIDO IP
ON
IP.PEDIDO_ID_PEDIDO = P.ID_PEDIDO
INNER JOIN 
PRODUTO PD
ON 
IP.PRODUTO_ID_PRODUTO = PD.ID_PRODUTO
INNER JOIN
STATUS_PEDIDO SP
ON 
SP.PEDIDO_ID_PEDIDO = P.ID_PEDIDO
INNER JOIN
CLIENTE C
ON 
P.CLIENTE_ID_CLIENTE = C.ID_CLIENTE
INNER JOIN
JURIDICA J  
ON
J.CLIENTE_ID_CLIENTE  = C.ID_CLIENTE
INNER JOIN
TELEFONE T
ON
T.CLIENTE_ID_CLIENTE = C.ID_CLIENTE 
INNER JOIN 
CLIENTE_ENDERECO CE
ON
CE.CLIENTE_ID_ENDERECO = C.ID_CLIENTE
INNER JOIN 
ENDERECO E
ON
CE.ENDERECO_ID_ENDERECO = E.ID_ENDERECO
INNER JOIN
ESTADO ES
ON
E.ESTADO_ID_ESTADO = ES.ID_ESTADO
INNER JOIN
PAGAMENTO PG
ON
PG.PEDIDO_ID_PEDIDO = P.ID_PEDIDO
INNER JOIN
FORMA FP
ON
PG.FORMA_ID_FORMA = FP.ID_FORMA
INNER JOIN
ENTREGA ENT
ON
P.ENTREGA_ID_ENTREGA  = ENT.ID_ENTREGA
INNER JOIN
FORMA_ENTREGA FENT
ON 
ENT.FORMA_ENTREGA_ID_FORMA_ENTREGA = FENT.ID_FORMA_ENTREGA
INNER JOIN
STATUS_ENTREGA SE 
ON
SE.ENTREGA_ID_ENTREGA = ENT.ID_ENTREGA
INNER JOIN
TIPO_STATUS_ENTREGA TSE
ON
TSE.STATUS_ENTREGA_ID_STATUS_ENTREGA = SE.ID_STATUS_ENTREGA	
UNION
SELECT
P.ID_PEDIDO AS CODIGO,
DATE_FORMAT(P.DATA_PEDIDO,  '%d-%m-%Y') AS 'DATA',
C.NOME AS NOME,
CONCAT(SUBSTR(F.ID_CPF, 1,9), '-', SUBSTR(F.ID_CPF, 10,11)) AS 'CPF/CNPJ',
C.EMAIL AS EMAIL,
CONCAT(T.DDD, ' ', SUBSTR(T.CELULAR, 1,5),'-', SUBSTR(T.CELULAR, 6,9)) AS CONTATO,
PD.DESCRICAO AS PRODUTO,
PD.VOLUME AS VOLUME,
PD.PESO AS PESO,
PD.PRECO AS PRECO,
IP.QUANTIDADE AS QUANTIDADE,
P.VALOR_TOTAL AS TOTAL,
E.APELIDO AS ENTREGA,
CONCAT(E.TIPO_LOGRADOURO,' ', E.NOME_LOGRADOURO, ' ','-', ' ', E.NUMERO) AS ENDERECO, 
CONCAT(SUBSTR(E.CEP, 1,5), '-', SUBSTR(E.CEP, 6,9) ) AS CEP,
CONCAT(E.CIDADE,'-',ES.SIGLA) AS MUNICIPIO,
SP.DESCRICAO AS STATUS_PEDIDO,
PG.STATUS_PAGAMENTO AS STATUS_PAGAMENTO,
FP.INSTITUICAO AS INSTITUICAO,
PG.VALOR_PAGAMENTO AS VALOR_PAGO,
DATE_FORMAT(PG.DATA_PAGAMENTO, '%d-%m-%Y') AS 'DATA',
FENT.EMPRESA AS ENTREGADOR,
ENT.PRAZO_ESTIMADO AS PRAZO_ENTREGA,
ENT.VALOR AS FRETE,
TSE.DESCRICAO AS STATUS_ENTREGA,
DATE_FORMAT(SE.DATA_ENTREGA, '%d-%m-%Y') AS 'DATA'
FROM
PEDIDO P
INNER JOIN
ITEM_PEDIDO IP
ON
IP.PEDIDO_ID_PEDIDO = P.ID_PEDIDO
INNER JOIN 
PRODUTO PD
ON 
IP.PRODUTO_ID_PRODUTO = PD.ID_PRODUTO
INNER JOIN
STATUS_PEDIDO SP
ON 
SP.PEDIDO_ID_PEDIDO = P.ID_PEDIDO
INNER JOIN
CLIENTE C
ON 
P.CLIENTE_ID_CLIENTE = C.ID_CLIENTE
INNER JOIN
FISICA F 
ON
F.CLIENTE_ID_CLIENTE  = C.ID_CLIENTE
INNER JOIN
TELEFONE T
ON
T.CLIENTE_ID_CLIENTE = C.ID_CLIENTE
INNER JOIN 
CLIENTE_ENDERECO CE
ON
CE.CLIENTE_ID_ENDERECO = C.ID_CLIENTE
INNER JOIN 
ENDERECO E
ON
CE.ENDERECO_ID_ENDERECO = E.ID_ENDERECO
INNER JOIN
ESTADO ES
ON
E.ESTADO_ID_ESTADO = ES.ID_ESTADO
INNER JOIN
PAGAMENTO PG
ON
PG.PEDIDO_ID_PEDIDO = P.ID_PEDIDO
INNER JOIN
FORMA FP
ON
PG.FORMA_ID_FORMA = FP.ID_FORMA
INNER JOIN
ENTREGA ENT
ON
P.ENTREGA_ID_ENTREGA  = ENT.ID_ENTREGA
INNER JOIN
FORMA_ENTREGA FENT
ON 
ENT.FORMA_ENTREGA_ID_FORMA_ENTREGA = FENT.ID_FORMA_ENTREGA
INNER JOIN
STATUS_ENTREGA SE 
ON
SE.ENTREGA_ID_ENTREGA = ENT.ID_ENTREGA
INNER JOIN
TIPO_STATUS_ENTREGA TSE
ON
TSE.STATUS_ENTREGA_ID_STATUS_ENTREGA = SE.ID_STATUS_ENTREGA;




