<<<<<<< HEAD
<<<<<<< HEAD
DROP TABLE ;
=======
/*-- DROP TABLE ;
>>>>>>> 29b5b77eea07f6485c978e0cab6c6e22791a6025
=======
/*-- DROP TABLE ;
=======
DROP TABLE ;
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
>>>>>>> 421972d200574f03f92aadedc3dc360b4ac2d26c
DROP DATABASE bd_politeismo;
--ATENCAO APAGA TODO O BANCO
SHOW TABLES;
create database bd_politeismo;
use bd_politeismo;
<<<<<<< HEAD
<<<<<<< HEAD
=======
*/
>>>>>>> 29b5b77eea07f6485c978e0cab6c6e22791a6025
=======
*/
=======
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
>>>>>>> 421972d200574f03f92aadedc3dc360b4ac2d26c
--                                                         TABLES


show tables; 


CREATE TABLE USER_ADM
(
<<<<<<< HEAD
ID_ADM	INT	NOT NULL AUTO_INCREMENT,
NOME	VARCHAR(255) NOT NULL,
CARGO	VARCHAR(255) NOT NULL,
EMAIL   VARCHAR(255) NOT NULL,
SENHA   VARCHAR(100) NOT NULL,
=======
ID_ADM			INT				NOT NULL 					AUTO_INCREMENT,
NOME			VARCHAR(255)	NOT NULL,
CARGO			VARCHAR(255) 	NOT NULL,
EMAIL   		VARCHAR(255) 	NOT NULL,
SENHA   		VARCHAR(100) 	NOT NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
PRIMARY KEY (ID_ADM)	
);

CREATE TABLE PRODUTO_DESTAQUE
(
<<<<<<< HEAD
ID_PRODUTO_DESTAQUE	INT	NOT NULL AUTO_INCREMENT,
DESCONTO DOUBLE	NOT NULL,
=======
ID_PRODUTO_DESTAQUE			INT				NOT NULL 		AUTO_INCREMENT,
DESCONTO 					DOUBLE			NOT NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
PRIMARY KEY	(ID_PRODUTO_DESTAQUE)
);

CREATE TABLE CATEGORIA
(
<<<<<<< HEAD
ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
=======
ID_CATEGORIA 		INT			 		NOT NULL 			AUTO_INCREMENT,
NOME 				VARCHAR(50)			NOT NULL,
FL_INATIVO			BOOLEAN				NOT NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE DEPARTAMENTO
(
<<<<<<< HEAD
ID_DEPARTAMENTO	INT	NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
=======
ID_DEPARTAMENTO		INT					NOT NULL 			AUTO_INCREMENT,
NOME 				VARCHAR(50)			NOT NULL,
FL_INATIVO			BOOLEAN				NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
PRIMARY KEY	(ID_DEPARTAMENTO)
);

CREATE TABLE FORNECEDOR
(
<<<<<<< HEAD
ID_FORNECEDOR INT NOT NULL AUTO_INCREMENT,
RAZAO_SOCIAL VARCHAR(100) NOT NULL,
CNPJ VARCHAR(14) NOT NULL UNIQUE,
EMAIL VARCHAR(100) NOT NULL,
TELEFONE varchar(250) NOT NULL,
=======
ID_FORNECEDOR 		INT 				NOT NULL 			AUTO_INCREMENT,
RAZAO_SOCIAL 		VARCHAR(100) 		NOT NULL,
CNPJ 				VARCHAR(14) 		NOT NULL 			UNIQUE,
EMAIL 				VARCHAR(100) 		NOT NULL,
FL_INATIVO			BOOLEAN		 		NULL,
TELEFONE 			varchar(250) 		NOT NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
PRIMARY KEY (ID_FORNECEDOR)
);

CREATE TABLE PRODUTO					
(
<<<<<<< HEAD
ID_PRODUTO 					INT						NOT NULL 			AUTO_INCREMENT,
=======
<<<<<<< HEAD
ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR(255) NOT NULL,
<<<<<<< HEAD
<<<<<<< HEAD
NOME VARCHAR (255) NOT NULL,
URL VARCHAR (255) NOT NULL,
=======
>>>>>>> 29b5b77eea07f6485c978e0cab6c6e22791a6025
=======
>>>>>>> 421972d200574f03f92aadedc3dc360b4ac2d26c
VOLUME DOUBLE NULL,
PESO DOUBLE NULL,
PRECO DOUBLE NOT NULL,
STATUS BOOLEAN NOT NULL,
ESTOQUE INT NULL,
FK_ID_PRODUTO_DESTAQUE INT NULL,
FK_ID_CATEGORIA	INT	NULL,
FK_ID_DEPARTAMENTO INT NULL,
FK_ID_FORNECEDOR INT NULL,
=======
ID_PRODUTO 					INT					NOT NULL 			AUTO_INCREMENT,
>>>>>>> bf78065b9461cca12f96c1fc45cae2a7bc334ede
DESCRICAO 					VARCHAR(255)			NOT NULL,
NOME 						VARCHAR (255) 			NOT NULL,
URL 						VARCHAR (255) 			NOT NULL,
VOLUME 						DOUBLE 					NULL,
PESO						DOUBLE 					NULL,
PRECO 						DOUBLE 					NOT NULL,
STATUS 						BOOLEAN 				NOT NULL,
ESTOQUE 					INT 					NULL,
FK_ID_PRODUTO_DESTAQUE 		INT						NULL,
FK_ID_CATEGORIA				INT						NULL,
FK_ID_DEPARTAMENTO 			INT 					NULL,
<<<<<<< HEAD
FK_ID_FORNECEDOR 			INT		 				NULL,
=======
FK_ID_FORNECEDOR 				INT 					NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
>>>>>>> bf78065b9461cca12f96c1fc45cae2a7bc334ede
PRIMARY KEY	(ID_PRODUTO),
FOREIGN KEY	(FK_ID_PRODUTO_DESTAQUE) REFERENCES PRODUTO_DESTAQUE (ID_PRODUTO_DESTAQUE),
FOREIGN KEY	(FK_ID_CATEGORIA)        REFERENCES CATEGORIA (ID_CATEGORIA),
FOREIGN KEY	(FK_ID_DEPARTAMENTO)     REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO),
FOREIGN KEY (FK_ID_FORNECEDOR)       REFERENCES FORNECEDOR (ID_FORNECEDOR)
);


CREATE TABLE CLIENTE
(
<<<<<<< HEAD
ID_CLIENTE 					INT	        		NOT NULL,
CPF	 						VARCHAR(14)      	NOT NULL 			UNIQUE,		
NOME 						VARCHAR(255)     	NOT NULL,
EMAIL 						VARCHAR(255)    	NOT NULL,
SENHA 						VARCHAR(255)    	NOT NULL,
NASCIMENTO 					DATE	       		NOT NULL,
FIXO	 					VARCHAR(11)		 	NULL,
CELULAR 					VARCHAR (12)		NULL,
=======
<<<<<<< HEAD
ID_CLIENTE INT        NOT NULL,
CPF VARCHAR(14)       NOT NULL UNIQUE,		
NOME VARCHAR(255)     NOT NULL,
EMAIL VARCHAR(255)    NOT NULL,
SENHA VARCHAR(255)    NOT NULL,
NASCIMENTO DATE       NOT NULL,
SEXO VARCHAR(225)     NOT NULL,
<<<<<<< HEAD
<<<<<<< HEAD
TELEFONE VARCHAR(11)  NULL,
CELULAR VARCHAR (12)  NULL,
=======
TELEFONE VARCHAR(225) NOT NULL,
>>>>>>> 29b5b77eea07f6485c978e0cab6c6e22791a6025
=======
TELEFONE VARCHAR(225) NOT NULL,
=======
ID_CLIENTE 					INT        		NOT NULL,
CPF	 					VARCHAR(14)      	NOT NULL 			UNIQUE,		
NOME 						VARCHAR(255)     	NOT NULL,
EMAIL 					VARCHAR(255)    	NOT NULL,
SENHA 					VARCHAR(255)    	NOT NULL,
NASCIMENTO 					DATE       		NOT NULL,
FIXO	 					VARCHAR(11) 	NULL,
CELULAR 					VARCHAR (12)	NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
>>>>>>> 421972d200574f03f92aadedc3dc360b4ac2d26c
>>>>>>> bf78065b9461cca12f96c1fc45cae2a7bc334ede
PRIMARY KEY (ID_CLIENTE)
);


CREATE TABLE ENDERECO
(
<<<<<<< HEAD
ID_ENDERECO INT              NOT NULL AUTO_INCREMENT,
APELIDO VARCHAR(255)         NOT NULL,
TIPO_LOGRADOURO VARCHAR(255) NOT NULL,
NOME_LOGRADOURO VARCHAR(255) NOT NULL,
NUMERO VARCHAR(5)            NOT NULL,
CEP VARCHAR(10)              NOT NULL,
CIDADE VARCHAR(50)           NOT NULL,
ESTADO VARCHAR(50)           NOT NULL,
FK_ID_FORNECEDOR INT         NOT NULL,
=======
ID_ENDERECO 				INT            		NOT NULL 		AUTO_INCREMENT,
APELIDO 					VARCHAR(255)       	NOT NULL,
NOME_LOGRADOURO 			VARCHAR(255) 		NOT NULL,
TIPO_LOGRADOURO 			VARCHAR(255) 		NOT NULL,
NUMERO 						VARCHAR(5)         	NOT NULL,
CEP 						VARCHAR(10)         NOT NULL,
CIDADE 						VARCHAR(50)       	NOT NULL,
BAIRRO						VARCHAR(255)		NOT NULL,
ESTADO						VARCHAR(255)		NOT NULL,
FK_ID_FORNECEDOR 			INT         		NOT NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
PRIMARY KEY (ID_ENDERECO),
FOREIGN KEY	(FK_ID_FORNECEDOR) REFERENCES FORNECEDOR (ID_FORNECEDOR)
);

CREATE TABLE CLIENTE_ENDERECO
(
<<<<<<< HEAD
CLIENTE_ID_CLIENTE 				INT			NOT NULL,
=======
<<<<<<< HEAD
CLIENTE_ID_CLIENTE INT   NOT NULL,
ENDERECO_ID_ENDERECO INT NOT NULL,
FOREIGN KEY (CLIENTE_ID_CLIENTE)  REFERENCES CLIENTE 	(ID_CLIENTE),
FOREIGN KEY (ENDERECO_ID_ENDERECO)REFERENCES ENDERECO 	(ID_ENDERECO)
);

CREATE TABLE FORMA
(
ID_FORMA INT             NOT NULL,
INSTITUICAO VARCHAR(255) NOT NULL,
PRIMARY KEY (ID_FORMA)
=======
CLIENTE_ID_CLIENTE 			INT		NOT NULL,
>>>>>>> bf78065b9461cca12f96c1fc45cae2a7bc334ede
ENDERECO_ID_ENDERECO 			INT 		NOT NULL,
FOREIGN KEY (CLIENTE_ID_CLIENTE)  REFERENCES CLIENTE 	(ID_CLIENTE),
FOREIGN KEY (ENDERECO_ID_ENDERECO)REFERENCES ENDERECO	(ID_ENDERECO)
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
);


CREATE TABLE BOLETO
(
<<<<<<< HEAD
ID_BOLETO INT                NOT NULL,
BANCO VARCHAR(50)            NOT NULL,
VENCIMENTO DATE              NOT NULL,
BENEFICIARIO VARCHAR(50)     NOT NULL,
NUMERO_DOCUMENTO VARCHAR(50) NOT NULL,
DATA_PROCESSAMENTO DATE      NOT NULL,
VALOR_COBRADO DOUBLE         NOT NULL,
FK_ID_FORMA INT              NOT NULL,
FK_ID_CLIENTE INT            NOT NULL,
PRIMARY KEY (ID_BOLETO),
FOREIGN KEY (FK_ID_FORMA)   REFERENCES FORMA (ID_FORMA),
=======
ID_BOLETO 				INT                NOT NULL,
BANCO 					VARCHAR(50)        NOT NULL,
VENCIMENTO 				DATE	           NOT NULL,
BENEFICIARIO 			VARCHAR(50)		   NOT NULL,
NUMERO_DOCUMENTO 		VARCHAR(50)		   NOT NULL,
DATA_PROCESSAMENTO 		DATE		       NOT NULL,
VALOR_COBRADO 			DOUBLE		 	   NOT NULL,
FK_ID_CLIENTE 			INT		           NOT NULL,
PRIMARY KEY (ID_BOLETO),
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
FOREIGN KEY (FK_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE PIX
(
<<<<<<< HEAD
ID_PIX 					INT              NOT NULL,
=======
<<<<<<< HEAD
ID_PIX INT         NOT NULL,
CHAVE VARCHAR(255) NOT NULL,
FK_ID_FORMA INT    NOT NULL,
FK_ID_CLIENTE INT  NOT NULL,
PRIMARY KEY (ID_PIX),
FOREIGN KEY	(FK_ID_FORMA)   REFERENCES FORMA (ID_FORMA),
FOREIGN KEY (FK_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE CARTAO
(
ID_NUMERO_CARTAO INT NOT NULL,
TITULAR VARCHAR(50)  NOT NULL,
VALIDADE DATE        NOT NULL,
CVV VARCHAR(3)       NOT NULL UNIQUE, 
FK_ID_FORMA INT      NOT NULL, 
FK_ID_CLIENTE INT    NOT NULL,
PRIMARY KEY (ID_NUMERO_CARTAO),
FOREIGN KEY (FK_ID_FORMA)   REFERENCES FORMA (ID_FORMA),
FOREIGN KEY (FK_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) 
);


CREATE TABLE ENTREGA 
(
ID_ENTREGA INT                NOT NULL AUTO_INCREMENT,
PRAZO DATE                    NOT NULL,
VALOR DOUBLE                  NOT NULL,
FORMA_ENTREGA VARCHAR(255)    NOT NULL, 
STATUS_ENTREGA VARCHAR(255)   NOT NULL,
=======
ID_PIX 					INT		       NOT NULL,
>>>>>>> bf78065b9461cca12f96c1fc45cae2a7bc334ede
CHAVE 					VARCHAR(255)	 NOT NULL,
FK_ID_CLIENTE 			INT  			 NOT NULL,
PRIMARY KEY (ID_PIX),
FOREIGN KEY (FK_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);


CREATE TABLE CARTAO
(
ID_CARTAO_NUMERO 		INT 			NOT NULL,
TITULAR_CARTAO 			VARCHAR(50)  	NOT NULL,
NUMERO_CARTAO			VARCHAR(20)		NOT NULL,
VALIDADE_CARTAO 		DATE        	NOT NULL,
FK_ID_CLIENTE 			INT				NOT NULL,
PRIMARY KEY (ID_CARTAO_NUMERO),
FOREIGN KEY (FK_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) 
);


<<<<<<< HEAD
=======
CREATE TABLE ENTREGA 
(
ID_ENTREGA 				INT              			NOT NULL		 AUTO_INCREMENT,
PRAZO 				DATE	           			NOT NULL,
VALOR 				DOUBLE          	   		NOT NULL,
FORMA_ENTREGA 			VARCHAR(255)			NOT NULL, 
STATUS_ENTREGA 			VARCHAR(255)			NOT NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
PRIMARY KEY (ID_ENTREGA)
);

>>>>>>> bf78065b9461cca12f96c1fc45cae2a7bc334ede
CREATE TABLE PEDIDO
(
<<<<<<< HEAD
ID_PEDIDO INT             NOT NULL AUTO_INCREMENT,
DATA_PEDIDO DATE          NOT NULL,
VALOR_TOTAL DOUBLE        NOT NULL,
CLIENTE_ID_CLIENTE INT    NOT NULL,
ENTREGA_ID_ENTREGA INT    NOT NULL,
STATUS_PEDIDO VARCHAR(50) NOT NULL,
PRIMARY KEY (ID_PEDIDO),
FOREIGN KEY	(CLIENTE_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY (ENTREGA_ID_ENTREGA) REFERENCES ENTREGA (ID_ENTREGA)
=======
ID_PEDIDO 				INT			        NOT NULL 		AUTO_INCREMENT,
DATA_PEDIDO 			DATE			    NOT NULL,
VALOR_TOTAL 			DOUBLE        	    NOT NULL,
STATUS_PEDIDO 			VARCHAR(50) 		NOT NULL,
FORMA_PAGAMENTO			VARCHAR(20)			NOT NULL,
FK_ID_CLIENTE 			INT   				NOT NULL,
FK_ID_ENDERECO 			INT	   			    NOT NULL,
PRIMARY KEY (ID_PEDIDO),
FOREIGN KEY	(FK_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
<<<<<<< HEAD
FOREIGN KEY (FK_ID_ENDERECO) REFERENCES ENDERECO (ID_ENDERECO)
=======
FOREIGN KEY (FK_ID_ENTREGA) REFERENCES ENTREGA (ID_ENTREGA)
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
>>>>>>> bf78065b9461cca12f96c1fc45cae2a7bc334ede
);


CREATE TABLE ITEM_PEDIDO
(
<<<<<<< HEAD
PRODUTO_ID_PRODUTO INT NOT NULL,
PEDIDO_ID_PEDIDO INT   NOT NULL,
QUANTIDADE INT         NOT NULL,
<<<<<<< HEAD
<<<<<<< HEAD
=======
PRIMARY KEY (PRODUTO_ID_PRODUTO, PEDIDO_ID_PEDIDO),
>>>>>>> 29b5b77eea07f6485c978e0cab6c6e22791a6025
=======
PRIMARY KEY (PRODUTO_ID_PRODUTO, PEDIDO_ID_PEDIDO),
>>>>>>> 421972d200574f03f92aadedc3dc360b4ac2d26c
FOREIGN KEY	(PRODUTO_ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO),
FOREIGN KEY (PEDIDO_ID_PEDIDO)   REFERENCES PEDIDO (ID_PEDIDO)
=======
ID_PRODUTO	 		INT 				NOT NULL,
ID_PEDIDO 			INT  				NOT NULL,
QUANTIDADE			INT         		NOT NULL,
FOREIGN KEY	(ID_PRODUTO)  REFERENCES PRODUTO (ID_PRODUTO),
FOREIGN KEY (ID_PEDIDO)   REFERENCES PEDIDO (ID_PEDIDO)
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
);


CREATE TABLE NOTA_FISCAL
(
<<<<<<< HEAD
ID_NOTA_FISCAL INT       NOT NULL AUTO_INCREMENT,
CODIGO_ACESSO_CHAVE INT  NOT NULL,
DATA_NOTA_FISCAL DATE    NOT NULL,
NUMERO_SERIE INT         NOT NULL,
VALOR DOUBLE             NOT NULL,
PEDIDO_ID_PEDIDO INT     NOT NULL,
OPERACAO VARCHAR(50)     NOT NULL,
PRIMARY KEY (ID_NOTA_FISCAL),
FOREIGN KEY	(PEDIDO_ID_PEDIDO)     REFERENCES PEDIDO (ID_PEDIDO)
=======
ID_NOTA_FISCAL 			INT       			NOT NULL		 AUTO_INCREMENT,
CODIGO_ACESSO_CHAVE 	INT  				NOT NULL,
DATA_NOTA_FISCAL 		DATE    			NOT NULL,
NUMERO_SERIE 			INT         		NOT NULL,
VALOR 					DOUBLE             	NOT NULL,
ID_PEDIDO	 			INT     			NOT NULL,
PRIMARY KEY (ID_NOTA_FISCAL),
FOREIGN KEY	(ID_PEDIDO)     REFERENCES PEDIDO (ID_PEDIDO)
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
);

CREATE TABLE ITEM_NOTA_FISCAL
(
<<<<<<< HEAD
ID_PRODUTO		 				INT	           	  NOT NULL,
ID_NOTA_FISCAL		 			INT	 			  NOT NULL,
QUANTIDADE 						INT		   	      NOT NULL,
=======
<<<<<<< HEAD
PRODUTO_ID_PRODUTO INT         NOT NULL,
NOTA_FISCAL_ID_NOTA_FISCAL INT NOT NULL,
QUANTIDADE INT                 NOT NULL,
PERCENTUAL DOUBLE              NOT NULL,
VALOR_ICMS DOUBLE              NOT NULL,
PRIMARY KEY (PRODUTO_ID_PRODUTO, NOTA_FISCAL_ID_NOTA_FISCAL),
FOREIGN KEY	(PRODUTO_ID_PRODUTO)         REFERENCES PRODUTO (ID_PRODUTO),
FOREIGN KEY (NOTA_FISCAL_ID_NOTA_FISCAL) REFERENCES NOTA_FISCAL (ID_NOTA_FISCAL)
=======
ID_PRODUTO		 				INT         	NOT NULL,
ID_NOTA_FISCAL		 			INT 			NOT NULL,
QUANTIDADE 						INT   	      NOT NULL,
>>>>>>> bf78065b9461cca12f96c1fc45cae2a7bc334ede
PERCENTUAL_ICMS					DOUBLE            NOT NULL,
VALOR_ICMS 						DOUBLE            NOT NULL,
PRIMARY KEY (ID_PRODUTO,ID_NOTA_FISCAL),
FOREIGN KEY	(ID_PRODUTO)    		REFERENCES PRODUTO (ID_PRODUTO),
FOREIGN KEY (ID_NOTA_FISCAL) 		REFERENCES NOTA_FISCAL (ID_NOTA_FISCAL)
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
);


CREATE TABLE PAGAMENTO
(
<<<<<<< HEAD
ID_PAGAMENTO INT NOT NULL AUTO_INCREMENT,
DATA_PAGAMENTO DATE NOT NULL,
STATUS_PAGAMENTO VARCHAR(50) NOT NULL,
VALOR_PAGAMENTO DOUBLE       NOT NULL,
PEDIDO_ID_PEDIDO INT         NOT NULL,
FORMA_ID_FORMA INT           NOT NULL,
PRIMARY KEY (ID_PAGAMENTO),
FOREIGN KEY	(PEDIDO_ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
FOREIGN KEY (FORMA_ID_FORMA)   REFERENCES FORMA (ID_FORMA)
=======
ID_PAGAMENTO 					INT 		NOT NULL 		AUTO_INCREMENT,
DATA_PAGAMENTO 					DATE 		NOT NULL,
FL_PAGAMENTO	 				VARCHAR(50) NOT NULL,
VALOR_PAGAMENTO 					DOUBLE      NOT NULL,
PEDIDO_ID_PEDIDO 					INT         NOT NULL,
PRIMARY KEY (ID_PAGAMENTO),
FOREIGN KEY	(PEDIDO_ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
);

CREATE TABLE FAVORITOS 
(
<<<<<<< HEAD
ID_FAVORITOS INT   NOT NULL,
<<<<<<< HEAD
<<<<<<< HEAD
=======
LISTA VARCHAR(255) NOT NULL,
>>>>>>> 29b5b77eea07f6485c978e0cab6c6e22791a6025
=======
LISTA VARCHAR(255) NOT NULL,
>>>>>>> 421972d200574f03f92aadedc3dc360b4ac2d26c
CLIENTE_ID_CLIENTE INT,
PRIMARY KEY (ID_FAVORITOS),
FOREIGN KEY (CLIENTE_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
=======
ID_FAVORITOS 				INT			   NOT NULL,
ID_CLIENTE		 			INT,
PRIMARY KEY (ID_FAVORITOS),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
);

CREATE TABLE PRODUTOS_FAVORITOS
(
<<<<<<< HEAD
PRODUTO_ID_PRODUTO INT     NOT NULL,
FAVORITOS_ID_FAVORITOS INT NOT NULL,
=======
PRODUTO_ID_PRODUTO 			INT			   NOT NULL,
FAVORITOS_ID_FAVORITOS 			INT			   NOT NULL,
>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
PRIMARY KEY (PRODUTO_ID_PRODUTO, FAVORITOS_ID_FAVORITOS),
FOREIGN KEY	(PRODUTO_ID_PRODUTO)     REFERENCES PRODUTO (ID_PRODUTO),
FOREIGN KEY	(FAVORITOS_ID_FAVORITOS) REFERENCES FAVORITOS (ID_FAVORITOS)
);

SHOW TABLES;

<<<<<<< HEAD
=======
SELECT * FROM  CLIENTE;

SELECT 
C.ID_CLIENTE,
C.NOME,
CONCAT(SUBSTR(CPF, 1,9), '-', SUBSTR(CPF, 10,11)) AS 'CPF',
C.EMAIL,
C.SENHA,
DATE_FORMAT(NASCIMENTO, '%d-%m-%Y') AS 'NASCIMENTO',
C.FIXO,
C.CELULAR,
E.APELIDO,
CONCAT(E.TIPO_LOGRADOURO, '-', E.NOME_LOGRADOURO, 'Nº ', E.NUMERO) AS 'ENDERECO',
E.CEP,
E.CIDADE,
E.BAIRRO,
E.ESTADO
FROM CLIENTE C
JOIN ENDERECO E
ON
E.ID_ENDERECO = C.ID_CLIENTE;

SELECT 
C.ID_CLIENTE,
C.NOME,
CONCAT(SUBSTR(CPF, 1,9), '-', SUBSTR(CPF, 10,11)) AS 'CPF',
C.EMAIL,
C.SENHA,
DATE_FORMAT(NASCIMENTO, '%d-%m-%Y') AS 'NASCIMENTO',
C.FIXO,
C.CELULAR
FROM CLIENTE C;

>>>>>>> 4c080c22c4c7cdd9603e7a8907c133b2dea15553
